### PR TITLE
VPS: Sync on any update

### LINKED ISSUE #465: Kubernetes PKI secret not updating
**Describe the bug**
I am using Terraform to deploy a VaultPKISecret resource linked to a kubernetes secret. When I update the VaultPKISecret to add additional alt names, these are reflected in the description of the resource. The operator then spits out logs saying it has synced the corresponding Kubernetes secret, however reading the secret shows its certificate to be unchanged, and not to include the new alt names.

**To Reproduce**
1. Deploy VaultPKISecret with a set of 5 alt names (as shows in terraform file below).
2. Update the resource to add an extra alt name (raise the range from `5` e.g. `7`).
3. Check VaultPKISecret to confirm it has added the alt names.
4. Check vault-operator logs to confirm it has synced the VaultPKISecret with the kubernetes secret
3. Check kubernetes secret to see it has not added the alt names.

Application deployment:

main.tf
```terraform
locals {
  cluster_name = "my-cluster"
  role_name    = "my_role"
  secret_name  = "${local.cluster_name}-cert-secret"
  hostnames = [for i in range(5) : "my-cluster-${i}.example.com"]
}

resource "kubernetes_namespace" "my_cluster" {
  metadata {
    name = local.cluster_name
  }
}

resource "kubernetes_service_account" "my_cluster" {
  metadata {
    name      = local.cluster_name
    namespace = kubernetes_namespace.my_cluster.metadata[0].name
  }
  automount_service_account_token = true
}

resource "kubectl_manifest" "vault_auth" {
  yaml_body = templatefile("vault_auth.tftpl", {
    auth_name            = local.cluster_name
    role_name            = local.role_name
    service_account_name = kubernetes_service_account.my_cluster.metadata[0].name
    namespace            = kubernetes_namespace.my_cluster.metadata[0].name

  })
  override_namespace = kubernetes_namespace.my_cluster.metadata[0].name
}

resource "kubectl_manifest" "vault_broker_cert" {
  yaml_body = templatefile("vault_broker_cert.tftpl", {
    auth_name   = local.cluster_name
    role_name   = local.role_name
    secret_name = local.secret_name
    common_name = local.cluster_name
    ttl         = "1d"
    alt_names   = local.hostnames
    ip_sans     = []
    other_sans  = []
    uri_sans    = []
    namespace   = kubernetes_namespace.my_cluster.metadata[0].name
  })
  override_namespace = kubernetes_namespace.my_cluster.metadata[0].name
}

module "vault" {
  source                         = "path/to/custom/vault/module"
  environment_name               = "dev"
  namespace_name                 = kubernetes_namespace.my_cluster.metadata[0].name
  service_account_name           = kubernetes_service_account.my_cluster.metadata[0].name
  allowed_domains                = concat([local.cluster_name], local.hostnames)
  organizational_unit            = "Max Levine ${local.cluster_name}"
  enable_pki_secret_backend_role = true
  role_name                      = local.role_name
  allow_ip_sans                  = true
  depends_on                     = [kubernetes_service_account.my_cluster]
}

```

vault_auth.tftpl
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ${auth_name}
  namespace: ${namespace}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ${role_name}
    serviceAccount: ${service_account_name}
    audiences:
      - vault
```

vault_broker_cert.tftpl
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  vaultAuthRef: ${auth_name}
  mount: pki_d2_ecdsa
  role: ${role_name}
  commonName: ${common_name}
  format: pem
  expiryOffset: 1s
  ttl: ${ttl}
#  revoke: true
  clear: true
  %{~ if length(ip_sans) > 0 ~}
  ipSans:
    %{~ for san in ip_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(other_sans) > 0 ~}
  otherSans:
    %{~ for san in other_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(uri_sans) > 0 ~}
  uriSans:
    %{~ for san in uri_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(alt_names) > 0 ~}
  altNames:
    %{~ for alt_name in alt_names ~}
    - ${alt_name}
    %{~ endfor ~}
  %{~ endif ~}
  destination:
    create: true
    name: ${secret_name}
    type: kubernetes.io/tls
```

**Expected behavior**
The kubernetes secret to be rotated to include the new alt names

**Environment**
* Kubernetes version: v1.25.10
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): GKE
  * Other configuration options or runtime services (istio, etc.): external-dns
* vault-secrets-operator version: v0.4.0

### PR DESCRIPTION
**Pull request by benashz**
Other VPS fixes:
- Sync whenever the destination secret is deleted and create=true
- Sync whenever the destination secret data is modified out of band
- Validate duration values for spec.ttl and spec.expiryOffset
- Remove extra enqueue handler that duplicated reconciliation of a VPS resource
- Add more test coverage for `internal/helpers/hmac.go`

Closes #465

### CODE REVIEW

File: controllers/vaultpkisecret_controller.go [hunk 1]
```diff
@@ -229,61 +218,89 @@ func (r *VaultPKISecretReconciler) Reconcile(ctx context.Context, req ctrl.Reque
...
 
-	if err := r.addFinalizer(ctx, logger, o); err != nil {
-		return ctrl.Result{}, err
-	}
-
 	logger.Info("Successfully updated the secret")
 	r.recordEvent(o, reason, "Secret synced")
 
+	horizon, _ := computePKIRenewalWindow(ctx, o, .05)
+	logger.Info("Requeue", "horizon", horizon)
```
Comment (tvoran) [inline controllers/vaultpkisecret_controller.go:282]: This might be good to log at debug level.

File: controllers/vaultpkisecret_controller.go [hunk 2]
```diff
@@ -292,25 +309,26 @@ func (r *VaultPKISecretReconciler) handleDeletion(ctx context.Context, l logr.Lo
 	return nil
 }
 
-func (r *VaultPKISecretReconciler) addFinalizer(ctx context.Context, l logr.Logger, s *secretsv1beta1.VaultPKISecret) error {
+func (r *VaultPKISecretReconciler) addFinalizer(ctx context.Context, s *secretsv1beta1.VaultPKISecret) (bool, error) {
```
Comment (tvoran) [inline controllers/vaultpkisecret_controller.go:312]: Is the `bool` return being used anywhere?

File: controllers/vaultpkisecret_controller.go [hunk 3]
```diff
@@ -374,27 +392,58 @@ func (r *VaultPKISecretReconciler) recordEvent(p *secretsv1beta1.VaultPKISecret,
 	r.Recorder.Eventf(p, eventType, reason, msg, i...)
 }
 
-func (r *VaultPKISecretReconciler) updateStatus(ctx context.Context, p *secretsv1beta1.VaultPKISecret) error {
+func (r *VaultPKISecretReconciler) updateStatus(ctx context.Context, o *secretsv1beta1.VaultPKISecret) error {
 	logger := log.FromContext(ctx)
-	metrics.SetResourceStatus("vaultpkisecret", p, p.Status.Valid)
-	if err := r.Status().Update(ctx, p); err != nil {
+	logger.V(consts.LogLevelDebug).Info("Update status called")
```
Comment (tvoran) [inline controllers/vaultpkisecret_controller.go:397]: Is there a trace log level available? Seems like this function would be called pretty frequently.

File: controllers/vaultpkisecret_controller.go [hunk 4]
```diff
@@ -292,25 +309,26 @@ func (r *VaultPKISecretReconciler) handleDeletion(ctx context.Context, l logr.Lo
...
-	return nil
 }
 
 // SetupWithManager sets up the controller with the Manager.
 func (r *VaultPKISecretReconciler) SetupWithManager(mgr ctrl.Manager) error {
 	return ctrl.NewControllerManagedBy(mgr).
 		For(&secretsv1beta1.VaultPKISecret{}).
-		// Add metrics for create/update/delete of the resource
-		Watches(&secretsv1beta1.VaultPKISecret{},
-			&handler.InstrumentedEnqueueRequestForObject{}).
```
Comment (tvoran) [inline controllers/vaultpkisecret_controller.go:313]: Curious why this was removed? Are those metrics gathered elsewhere?

**Review by tvoran — COMMENTED** [review]
Got about halfway through, just a few questions so far.

File: controllers/vaultpkisecret_controller.go (hunk 3 above)
Comment (benashz) [reply controllers/vaultpkisecret_controller.go:397]: I don't think so, but we easily add a new log level.

File: controllers/vaultpkisecret_controller.go (hunk 4 above)
Comment (benashz) [reply controllers/vaultpkisecret_controller.go:313]: It was causing the VDS CR to be reconciled twice.

Comment (benashz) [reply controllers/vaultpkisecret_controller.go:313]: Sorry, I missed your second question. Yes we are still getting the same controller_* metrics for each controller:
e.g:  
```
# HELP controller_runtime_reconcile_errors_total Total number of reconciliation errors per controller
# TYPE controller_runtime_reconcile_errors_total counter
controller_runtime_reconcile_errors_total{controller="hcpauth"} 0
controller_runtime_reconcile_errors_total{controller="hcpvaultsecretsapp"} 0
controller_runtime_reconcile_errors_total{controller="vaultauth"} 0
controller_runtime_reconcile_errors_total{controller="vaultconnection"} 1
controller_runtime_reconcile_errors_total{controller="vaultdynamicsecret"} 0
controller_runtime_reconcile_errors_total{controller="vaultpkisecret"} 1
controller_runtime_reconcile_errors_total{controller="vaultstaticsecret"} 0
```

File: go.mod [hunk 5]
```diff
@@ -19,15 +19,14 @@ require (
 	github.com/hashicorp/vault/sdk v0.10.2
 	github.com/onsi/ginkgo v1.16.5
 	github.com/onsi/gomega v1.30.0
-	github.com/operator-framework/operator-lib v0.11.1-0.20230717184314-6efbe3a22f6f
 	github.com/prometheus/client_golang v1.17.0
 	github.com/prometheus/client_model v0.5.0
 	github.com/stretchr/testify v1.8.4
-	google.golang.org/api v0.151.0
+	google.golang.org/api v0.150.0
```
Comment (kschoche) [inline go.mod:25]: Any particular reason for the go mod downgrades?

**Review by kschoche — APPROVED** [review]
Great work, I left a few non-blocking comments/questions but I like the changes.
👍🏽 assuming @tvoran didn't have any blockers.

File: controllers/vaultpkisecret_controller.go (hunk 4 above)
Comment (tvoran) [reply controllers/vaultpkisecret_controller.go:313]: > It was causing duplicate CR reconciliation. One for For() and one for Watches(). That's what was causing the failed status updates, and extra rotations.

Hmm, I'm not seeing any of that when testing a build off main with the PKI samples.

Either way I'm fine with removing it here, since it isn't present on any of the other controllers.

Comment (benashz) [reply controllers/vaultpkisecret_controller.go:313]: If you have `-zap-log-level=5` set on the manager, you will see the duplicate enqueuing. Different reconcile IDs within quick succession.

File: controllers/vaultpkisecret_controller.go [hunk 6]
```diff
@@ -229,61 +218,89 @@ func (r *VaultPKISecretReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 		}
 		data[corev1.TLSPrivateKeyKey] = data["private_key"]
 	}
+
+	if b, err := json.Marshal(data); err == nil {
+		newMAC, err := r.HMACValidator.HMAC(ctx, r.Client, b)
+		if err != nil {
+			logger.Error(err, "HMAC data")
+			o.Status.Error = consts.ReasonHMACDataError
+			if err := r.updateStatus(ctx, o); err != nil {
```
[the remark this answers is not in the document]
Comment (benashz) [reply controllers/vaultpkisecret_controller.go:224]: I think this is to be consistent with the the way other errors are handled. We have `spec.status.valid` to set to `false` on error. We can probably get rid of that field at some point.

File: controllers/vaultpkisecret_controller.go (hunk 3 above)
Comment (benashz) [reply controllers/vaultpkisecret_controller.go]: Updated in d7a5ad7c97a73d39d8f253fca0ae8c3f4965d8d0

File: controllers/vaultpkisecret_controller.go (hunk 2 above)
Comment (benashz) [reply controllers/vaultpkisecret_controller.go]: Good catch, updated in d7a5ad7c97a73d39d8f253fca0ae8c3f4965d8d0

File: controllers/vaultpkisecret_controller.go (hunk 1 above)
Comment (benashz) [reply controllers/vaultpkisecret_controller.go]: Dropped it with  d7a5ad7c97a73d39d8f253fca0ae8c3f4965d8d0

File: controllers/common.go [hunk 7]
```diff
@@ -39,30 +39,36 @@ func (l *LeaseTruncatedError) Error() string {
...
+func computeMaxJitter(duration time.Duration) (float64, uint64) {
 	return computeMaxJitterWithPercent(duration, 0.1)
 }
 
 // computeMaxJitter with max as a percentage (percent) of the duration, and
 // jitter a random amount between 0 up to percent
-func computeMaxJitterWithPercent(duration time.Duration, percent float64) (max float64, jitter uint64) {
-	max = percent * float64(duration.Nanoseconds())
-	u := uint64(max)
+func computeMaxJitterWithPercent(duration time.Duration, percent float64) (float64, uint64) {
```
[the remark this answers is not in the document]
Comment (benashz) [reply controllers/common.go]: reverted

**Review by tvoran — APPROVED** [review]
Works great for me testing locally 👍

File: controllers/vaultpkisecret_controller.go [hunk 8]
```diff
@@ -375,27 +404,61 @@ func (r *VaultPKISecretReconciler) recordEvent(p *secretsv1beta1.VaultPKISecret,
...
 
-func getRenewTime(expiration int64, offset time.Duration) time.Duration {
-	renewTime := time.Unix(expiration-int64(offset.Seconds()), 0)
-	return renewTime.Sub(time.Now())
+func computePKIRenewalWindow(ctx context.Context, o *secretsv1beta1.VaultPKISecret,
+	jitterPercent float64,
+) (time.Duration, bool) {
+	logger := log.FromContext(ctx).WithValues("expiryOffset", o.Spec.ExpiryOffset)
+	if o.Status.LastRotation > 0 {
+		// TODO: factor out lastRotation when we add support for spec.renewalPercent
```
[the remark this answers is not in the document]
Comment (benashz) [reply controllers/vaultpkisecret_controller.go:430]: I thought we might support both, with `renewalPercent` taking precedent over `expiryOffset`. Not sure if that might confuse things, though. It's definitely worth further discussion.
