### PR TITLE
Make some recently required bool parameters optional

### LINKED ISSUE #631: Breaking changes to v1beta1 VaultStaticSecret and VaultConnection CRDs cause failed upgrades after v0.5.0
**Describe the bug**
Additional required fields have been added to the VaultConnection and VaultStaticSecret CRDS without bumping the api version:

https://github.com/hashicorp/vault-secrets-operator/blob/6de064379dc95617133056aca00213453a04f07b/chart/crds/secrets.hashicorp.com_vaultconnections.yaml#L59-L61

https://github.com/hashicorp/vault-secrets-operator/blob/6de064379dc95617133056aca00213453a04f07b/chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml#L178-L181

The new fields have default values but defaults are only applied when new instances of the CRDs are created. This means any in-flight CRD instances that exist in a given cluster will now break the operator and block the upgrade:

**To Reproduce**
1. Deploy a version of VSO older than v0.5.0
2. Deploy a VaultConnection or VaultStaticSecrets CRD
3. Upgrade the VSO operator past v0.5.0
6. Operator fails to upgrade:

MicrosoftTeams-image

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection-test
  namespace: default
spec:
  address: https://some-vault-url.com
  caCertSecretRef: some--ca-cert
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: vault-static-secret-test
spec:
  vaultAuthRef: vault-auth-test
  mount: some-namespace/secret
  type: kv-v2
  path: sample
  refreshAfter: 60s
  destination:
    create: true
    name: vault-static-secret-test
```

**Expected behavior**
Operator upgrades successfully

**Environment**

* Kubernetes version: 
* OpenShift 4.14
* 
* vault-secrets-operator version:
* v0.5.1

### PR DESCRIPTION
**Pull request by tvoran**
(Just putting this up as an option to address #631 if we wish.)

Makes some currently required `bool` parameters optional, but keeps the default of `false`, so that the value can effectively be set to `false` in k8s storage. The secret destination options were added in v0.5.0.

I was able to duplicate the upgrade error in #631 on OpenShift outside of OperatorHub with `operator-sdk run bundle...` and `operator-sdk run bundle-upgrade...`, which would fail when going from v0.4.3 to v0.5.x, but succeed when going from v0.4.3 to these changes.

<details>
  <summary>Details for posterity:</summary>

```bash
$ oc new-project vault-secrets-operator

$ operator-sdk run bundle -n vault-secrets-operator registry.connect.redhat.com/hashicorp/vault-secrets-operator-bundle:0.4.3

# deploy a VaultStaticSecret setup
...

# upgrade the operator
$ operator-sdk run bundle-upgrade -n vault-secrets-operator registry.connect.redhat.com/hashicorp/vault-secrets-operator-bundle:0.5.1

# ^ this will eventually timeout, with an error like this in the status of the subscription:
$ kubectl get subscription -n vault-secrets-operator vault-secrets-operator-v0-4-3-sub -o yaml
...
    message: 'error validating existing CRs against new CRD''s schema for "vaultstaticsecrets.secrets.hashicorp.com":
      error validating custom resource against new schema for VaultStaticSecret tenant-1/static-demo:
      [].spec.destination.overwrite: Required value'
...

# Build a bundle from this branch
$ export PREVIOUS_VERSION=v0.5.1
$ export TEST_VERSION=0.5.2-test-olm-upgrade
$ make ci-build ci-docker-build-ubi VERSION=${TEST_VERSION?}
$ docker tag hashicorp/vault-secrets-operator:${TEST_VERSION?}-ubi <docker-repo>:${TEST_VERSION?}-ubi
$ docker push <docker-repo>:${TEST_VERSION?}-ubi

$ make bundle IMG=<docker-repo>:${TEST_VERSION?} IMG_UBI=<docker-repo>:${TEST_VERSION?}-ubi VERSION=${TEST_VERSION?} USE_IMAGE_DIGESTS=true
$ make bundle-build BUNDLE_IMG=<docker-repo>-bundle:${TEST_VERSION?}
$ docker push <docker-repo>-bundle:${TEST_VERSION?}

# start over from the beginning, but do the bundle-upgrade with this branch, and the upgrade passes
...
$ operator-sdk run bundle-upgrade -n vault-secrets-operator docker.io/<docker-repo>-bundle:0.5.2-test-olm-upgrade
```

</details>

Closes #631

### CODE REVIEW

**Review by tomhjp — APPROVED** [review]
I'm supportive of this approach 👍 it always looked a bit wrong to me that these parameters were marked as required

File: api/v1beta1/vaultconnection_types.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ type VaultConnectionSpec struct {
 	CACertSecretRef string `json:"caCertSecretRef,omitempty"`
 	// SkipTLSVerify for TLS connections.
 	// +kubebuilder:default=false
-	SkipTLSVerify bool `json:"skipTLSVerify"`
+	SkipTLSVerify bool `json:"skipTLSVerify,omitempty"`
```
Comment (benashz) [inline api/v1beta1/vaultconnection_types.go:25]: I think this one we want to keep as-is. We made this change under #527 - to avoid an issue with Rancher.

**Review by benashz — APPROVED** [review]
We should revert the change made to SkipTLSVerify, after that +1

**Comment by benashz** [comment]
> I'm supportive of this approach 👍 it always looked a bit wrong to me that these parameters were marked as required

@tomhjp - yeah its unfortunate that fields with defaults are not excluded from the set of required fields, or that the validators do not take defaults into account.

File: api/v1beta1/vaultconnection_types.go (hunk 1 above)
Comment (tvoran) [reply api/v1beta1/vaultconnection_types.go:25]: We can certainly do that, especially since this has been in place since v0.4.3.

FWIW in my testing this behaves the same with or without `omitempty` when there's a default set. If the parameter is set to true/false in the CRD spec it comes back on a get. And if the parameter is unspecified it comes back as `false` on a get. Which I think satisfies #527 and #278.

File: config/manifests/bases/vault-secrets-operator.clusterserviceversion.yaml [hunk 2]
```diff
@@ -168,4 +168,7 @@ spec:
   provider:
     name: HashiCorp
     url: https://www.hashicorp.com/
+  skips:
+  - vault-secrets-operator.v0.5.0
+  - vault-secrets-operator.v0.5.1
```
Comment (tvoran) [inline config/manifests/bases/vault-secrets-operator.clusterserviceversion.yaml:173]: Because of these I think we'll want to use PREVIOUS_VERSION=v0.4.3 with `make bundle`:

```
make bundle VERSION=${LATEST_TAG//v} USE_IMAGE_DIGESTS=true PREVIOUS_VERSION=v0.4.3
```

So that the resulting `build/bundle/manifests/vault-secrets-operator.clusterserviceversion.yaml` comes out like this:

```yaml
  skips:
    - vault-secrets-operator.v0.5.0
    - vault-secrets-operator.v0.5.1
  version: 0.5.2
  replaces: vault-secrets-operator.v0.4.3
```
